atheurer/trafficgen

- trafficgen.lua
This commit also requires changes to our process to
pull moongen & phobos repos and checkout at approproate
commit ID
> Fix code to allow use of latest Moongen and Phobos levels

- trafficgen.lua
- Defaulting a value to true is a lot different than defaulting it to
false
> Config loading logic fix

- README.md
Updated instructions upon how to install lua-trafficgen/MoonGen.  Needed for VSPERF project but also everyone in general.
> Update README.md with MoonGen set up instructions

- trafficgen.lua
- The binary search proceeds normally until the search rate drops
below the specified minimum rate (defaults to zero).  If that
happens, the next test rate is set to the minimum rate.  If a rate
fails and it is equal to the minimum rate then the test fails.
------------
I started out trying to implement what we discussed last week with testing the minimum rate up front and then using that information going forward.  That starting resulting in a lot of code duplication (negative packet loss checks, rate checks, etc.) so I decided to go in a different direction.  The way it is implemented now the search will run normally and only deviate if the next rate to attempt falls below the requested minimum rate.  This allows for very little code change while also limiting change in flow as much as …
> Add support for a minimum rate and fail if it can not be achieved

- trex-txrx.py
- Add library paths to enable the script to execute, regardless of
location.  Without adding the paths the script can only be executed
if it exists in the stl examples directory (which is added first).
- Initialize the stats variable outside the try statement so that it
is scoped to the finally statement.
- Ensure that the result stats are printed in two forms: a human
readable form and a parsable form for consumption by another program
(binary-search.py).
- The variables that come from command line arguments exist in the
t_global.args namespace so they must be referenced that way.
- The test length is stored in the t_global.args.runtime and not
t_global.args.duration.
- Print a statement for each direction that packets are flowing to
more accurately portray if the test is unidirectional …
> Fix a bunch of issues with trex-txrx.py

- binary-search.py
- There are still quite a few parameters that need to be implemented
(ex. flow mods) but this provides the basic support that is required
to run a binary search.
> Implement initial support for trex-txrx.py in binary-search.py

- trex-txrx.py
- This ensures that the tested rate is the requested rate whether or
not latency monitoring is enabled.
> Adjust the trex rate multiplier if latency is enabled

- binary-search.py
- trex-txrx.py
- Segment statistics are monitored to determine if a trial should be
terminated prematurely in order to optimize runtime.  Segment stats
are checked by a monitor thread and once segment N has TXed packets,
segment N-2 is analyzed to see if it passed the loss requirement.
This ensures that all packets for segment N-2 should have traversed
path from from and back to the traffic generator.
- Also log all TRex events (not just warnings) in case they contain
useful information.
- Cleanup CTRL+C behavior to be very explicit in it's behavior and
create the notion of "Forced Quit".
> binary-search.py & trex-txrx.py: add segment monitoring

- trex-txrx.py
- Properly generate N flows when N flows are requested, rather than
N+1
- Only enable flow modifiers if they are requested and the flow count
is greater than 1.  Likewise, only update the checksums if flow
modifiers are enabled and the flow count is greater than 1.
- Don't duplicate code when constructing packet to avoid potential
sync issues down the road
> trex-txrx.py: correct and cleanup flow generation

- binary-search.py
- trex-txrx.py
-- Move to more consistent naming mechanisms based on traffic
direction and port indexes.
> binary-search.py & trex-txrx.py: remove the A and B port designations

- trex-txrx.py
- When stream_mode == "burst" and the number of packets that are
calculated for the stream (packet rate * runtime) exceeds the value
that a uint32 can hold the stream must be broken into multiple
pieces.  Each newly created stream is configured to send a number of
packets <= the maximum value that a uint32 can hold.  The new
streams are inserted into the existing stream or set of streams and
programmed to execute in order.  The new streams all use the same
PG_ID so that the resulting statistics are unaware that this
modification was required, so no result processing changes are
required.  The stream changes are logged, but not surfaced in the
stream configurations consumed by binary-search.py since this
modification should be invisible.
> trex-txrx.py: fix stream_mode == "burst" problem with too many packets

- trex-txrx.py
- Honor and use the global variable t_global to access command line
parameters.
- This simplifies the code significantly and removes the requirement
of having to pass the parameters through the various levels of code
(which is likely to increase in the future).
> trex-txrx.py: code cleanup

- binary-search.py
Merge the commits for per direction stats
> Directional stats

- binary-search.py
- Allow the user to specify how to respond to negative packet loss.
The options are:
fail (the trial)
quit (the entire search)
retry-to-fail (the trial)
retry-to-quit (the trial)
The retry-to-* options will retry the trial up to --max-retries and
once the retries are exhausted will follow the action specified by
the * (fail or quit).
> binary-search.py: update negative packet loss handling

- binary-search.py
> binary-search.py: include log in binary_search.json

- launch-trex.sh
- Returning devices to the Linux kernel driver can be an iterative
process since the TRex utility only does 2 devices at a time
(despite the fact that it claims to return all devices).  In order
to get all devices, and potentially the correct devices, returned to
the kernel call the script in a loop until there are no more
references to vfio-pci.
- Update the temporary config file handling to be stored in the
temporary directory without having to mess with /etc.  The temporary
config file usage is now explicit rather than implicit which should
make comprehension of the script and what it is doing more
straightforward.
> launch-trex.sh: more TRex v2.53 related updates

- binary-search.py
- New support for a warmup trial introduces a user enabled trial that
is run prior to the true binary search as a way of warming up an
environment.  The packet loss results of the warmup trial are
ignored, but it does respect the basic functionality requirements
such as packets received and packets being received on the proper
port.
- For the trex-txrx-profile.py traffic generator there is support for
specifying a traffic profile that is different than the one that
will be run during the binary search.  For other traffic generators
the traffic run during the warmup will be the same as what is run
during the binary search.
- The user can define a runtime for the warmup trial that is
independent of the other trial runtimes.
- If both the warmup trial option and the one shot trial option are …
> binary-search.py: add the concept of a warmup trial

- binary-search.py
- Allow the user to disable upward search if desired
- Prevent the upward search from increasing the rate past 100.0 when
the traffic generator is trex-trx and the rate unit is % (since 100%
indicates line rate).
> binary-search.py: add upward search controls

- .gitmodules
Include fleitner's XenaPythonLib as a submodule  of trafficgen; preliminary step to add Xena capabilities to binary-search.py
> Add XenaPythonLib submodule

- xena-txrx.py
Implements basic argument parsing capabilities to match xena trial parameters in binary-search.py. Adds parser arguments, a print function, and necessary import statements.
> implement basic argument parser

- binary-search.py
Minor cosmetic change, no discernible impact on functionality or performance.
> fix typos in parser help text

- README-binary-search.md
- This README was pretty stale and not accurate given the current
landscape in trafficgen so refresh it to be more applicable to the
current state of the project.
> README-binary-search.md: make current

- install-trex.sh
- Notably this version addresses some issues with X710 firmware that
at least one person using trafficgen has experienced.
> install-trex.sh: update to v2.82
