trafficgen.lua

Lots of latency related changes and a few generic items.  Specifically address issues #7 and #3.
- By default negative packet loss results in up to 3 retries before the attempted speed is marked as a failure.  This can be overriden to achieve the current behavior of accepting negative packet loss as success.
- Print the final report on every attempt but label it as RESULT instead of REPORT
- Log all latency samples for jitter analysis.
- Set latency packet size to requested packet size.  If size < 76 then UDP packets are no longer used for latency measurements.
- Dump the testParams after loading the config file for validation

Latency (and other) updates

---

trafficgen.lua

There are two main updates here:
1. Lower the maximum latency packet timeout value.  This appears to improve accuracy for me.
2. Resolve the lua panic that is seen when large amounts of memory are consumed by the latency sample log. I used information from these links: [http://luajit.org/ext_ffi.html](http://luajit.org/ext_ffi.html) and [http://luajit.org/ext_ffi_api.html](http://luajit.org/ext_ffi_api.html).  I was originally going to use [https://github.com/torch/tds](https://github.com/torch/tds) but as I dug into that I decided the dependencies and complexity of integrating it into MoonGen's luajit was overly complicated.

Latency Updates

---

trafficgen.lua

1. Adds possibility to specify logging level.
2. Limits stats which are continuously printed by 'stats' library.
See #18

Logging improvements

---

binary-search.py
trex-txrx.py

- The flow/stream packet rates do not appear to be correctly
calculated so the packet rates are manually determined.
- Restructure the code to make changing the statistics that
binary-search.py consumes easier to tweak.
Addresses issue #30

Update trex-txrx.py to use flow/stream stats instead of device stats

---

binary-search.py

- Disable output buffering for binary-search.py using the -u Python
option
- Handle the subprocess output gracefully as it is produced

Resolve output buffering issues with binary-search.py

---

binary-search.py
trex-txrx.py

Adds the ability to set the rate as a percentage of port bandwidth (ie. 75% of 40Gb is 30Gb).
Also fixes a bug in the processing of the packet generator's output which could cause the binary search to exit prematurely with an error.

Trex updates

---

trex-txrx.py

- Uncomment the line "the_packet.show2()" to get a dump of the scapy
generated packet (prior to flow modifications) at the beginning of
the trial.
- You will get a packet dump for each call to creake_pkt, ie. each
active stream (undidirectional vs. bidirectional and/or latency on
vs. latency off).
- This can be useful for debugging and packet tracing purposes.
- Eventually this might be cleaned up with a verbose/debug mode so
that code modification isn't required.

trex-txrx.py: Improving debugging capabilities of packet creation

---

binary-search.py

- This has the downstream affect of allowing the postprocessing script
to check for the presence of these variables in the JSON output to
determine the proper course of action to take.

binary-search.py: remove trex specific stats from moongen

---

binary-search.py
trex-txrx.py

- The new revunidirec traffic direction allows a unidirectional test
to be run in the opposite direction of the existing unidirec test
scenario.

binary-search.py and trex-txrx.py: add revunidirec

---

binary-search.py

-- This ensures that the logging that trex-txrx.py provides is
consistent with the test being run.  Without this change
trex-txrx.py would log it's default value for --max-loss-pct which
might not agree with the search that is being run by
binary-search.py.  This could happen when a non-default
--max-loss-pct value was specified to binary-search.py and the test
was not using segmented streams with the segment stream monitor.

binary-search.py: always pass the --max-loss-pct value to trex-txrx.py

---

launch-trex.sh
trex-txrx.py

I was able to send vlan tag on x710 with this change. Pay attention to the 64 byte frame size special handing - when we specify 64 byte frame size, the expected l2 size is 64 byte - 4 byte of CRC = 60 bytes, but I  had to increase the L2 size to 64 byte, otherwise trex server will complain about the 60 byte of L2 size. I think that's a trex issue.

vlan tag added

---

trex-txrx.py

- The number of protocols being used has to be accounted for when
computing runtimes.

trex-txrx.py: segmented streams runtime bugfix

---

binary-search.py
trex-txrx.py

- The recently introduced GARP infrastructure is being morphed into a
more generic fabric teaching framework.  The fabric teaching
framework will be more flexible, allowing for different tuning
parameters between warmup and measurement phases and eventually
different packet types.  The purpose of fabric teaching is to allow
the operator to "teach" the networking fabric of the location of
various devices (real of virtual) so that packets can be properly
routed to their destinations.
- The teaching warmup (formerly GARP warmup) has also had it's timeout
infrastructure updated to adjust to user supplied tuning parameters
and to more gracefully handle a potential timeout scenario.

binary-seach.py & trex-txrx.py: introduce concept of fabric teaching

---

binary-search.py

001:TRex Events:
001:    EVENT: 2018-08-16 06:08:13 - [server][info]     - Port 0 has started
001:    EVENT: 2018-08-16 06:08:13 - [server][info]     - Port 1 has started
001:    EVENT: 2018-08-16 06:09:13 - [server][info]     - Port 0 job done
001:    EVENT: 2018-08-16 06:09:13 - [server][info]     - Port 1 job done
001:TX Utilization: 7.898000%
001:RX Utilization: 0.000629%
001:TX Queue Full:  0
001:Disconnecting from TRex server...
001:Connection severed
We hit this kind of error, fix this typo error.
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib64/python2.7/threading.py", line 812, in __bootstrap_inner
self.run()
File "/usr/lib64/python2.7/threading.py", line 765, in run
self.__target(*self.__args, **self.__kwargs)
File "./binary-search.py", line …

fix an possible typo error

---

trex_tg_lib.py

- Make sure a trex profiler sample includes a ['pgid']['latency']
property before accessing it.
- It appears that a timing issue could cause this field to not exist
yet when a sample is collected (this is somewhat speculative).

trex_tg_lib.py: ensure trex profile property exists

---

trex_tg_lib.py

- When trex-txrx is being used there is code further up the stack that
avoids this error, but in trex-txrx-profile the execution can reach
this point without having validated the value so provide a mechanism
for handling the error case.
- It probably is wise to always have a proper default "else" clause
regardless of what the expectation of upstream validations is.

trex_tg_lib.py: catch a corner case error in create_generic_pkt

---

binary-search.py

- Avoid amplification caused by performing a += operation using a
value that itself is being calculated using +=.  This was causing
some values to be factored into the summation multiple times in some
situations (depending on looping).

binary-search.py: summation amplification bug fix

---

install-trex.sh
launch-trex.sh

- This update requires a change in the way device driver binding is
handled when L2 mode is used.

update Trex from version 2.46 to 2.53

---

binary-search.py

- Check for the presence of TX latency packets (ie. > 0) before using
it as the divisor.  In trex-txrx-profile.py it is possible for
streams to have latency packets disabled in the profile definition
even though latency analysis is enabled at the global level.  If a
stream has latency packets disabled while latency analysis is
enabled globally then during analysis of the trial results a divide
by zero error would occour.

binary-search.py: correct divide by zero bug

---

trex-txrx-profile.py

- This ensures that we never generate a packet count equal to 0 which
causes TRex to abort.
- Also add a comment explaining this slightly odd looking block of
code

trex-txrx-profile.py: round packet count up rather than down

---

binary-search.py

- Add support for --loss-granularity=direction when --use-device-stats
is specified.

binary-search.py: bug fix for --use-device-stats

---

trex-txrx.py

- We expect the result of these calculations to be integers but with
Python3 they are floats so we have to cast them.

trex-txrx.py: bug fix for python3 int/float behavior

---

trex-txrx-profile.py

- We expect the result of these calculations to be integers but with
Python3 they are floats so we have to cast them.

trex-txrx-profile.py: bug fix for python3 int/float behavior

---

.gitmodules
binary-search.py

The changes made allow a user to specify xena as a traffic generator in the program arguments. New code added in functions main() and run_trial() is the bare minimum necessary to avoid script crash when --traffic-generator=xena. Xena functionality in binary-search.py is currently limited to printing a confirmation message of the user's selection and exiting.

Add --traffic-generator option 'xena'

---

binary-search.py

Adds three new arguments to process_options(): --user, --pwd, and --chassis for use with Xena/XenaPythonLib. Includes accompanying help messages for each argument. Argument names were chosen so they would be reasonably distinct from other pre-existing options, in the hope of reducing possible confusion.

Add 'user', 'pwd', and 'chassis' parser arguments for working with Xena

---

binary-search.py

Xena trial parameters are compiled into string cmd, which represents a command to be issued via terminal to xena-txrx.py. Minimal trial parameters are currently included - the next step is to implement the argument parser in xena-txrx. Additional trial parameters will be included once basic functionality is in place.

add basic trial param to xena

---

xena-txrx.py

Incorporates basic XenaPythonLib functionality by connecting to a Xena chassis. Failed connection attempts trigger an exception and print an error message. Successful connection prints a status message, waits five seconds, then disconnects from the server.
Note: xena-txrx.py exits gracefully if called directly from cli (ex: python -u xena-txrx.py --xena_chassis=11.11.11.11 --xena_user=userX). If called from binary-search.py (ex: python3 binary-search.py --traffic-generator=xena --xena_user=userX --xena_chassis=11.11.11.11) the parent script crashes in def evaluate_trial() (after running xena-txrx). This behavior is expected because of xena-txrx's currently limited functionality, and will be addressed in the next patch.
*this pull request corrects procedural …

add chassis connect/disconnect

---

launch-trex.sh

- This makes it work on both RHEL7 AND RHEL8 tmux.

launch-trex.sh: fixup quoting of tmux command

---

xena-txrx.py

Adds additional Xena functionality. Begins a manager session using the supplied parser arguments. Reserves ports 0 and 1 (currently hard-coded for development and testing purposes). Ends by disconnecting from Xena.

Add ports to Xena, close chassis connection

---

binary-search.py
trex-txrx-profile.py
trex-txrx.py

- This adds runtime support to the scripts involved in running the
test (binary-search.py, trex-txrx.py, and trex-txrx-profile.py).
- This is no way addresses installing, configuring, and/or launching
TRex on the remote host.

add minimal support for remote TRex hosts

---

binary-search.py

- When trex-txrx.py is used with the segment monitor enabled it is
possible for a trial to exit before a stream is run.  When this
happens there is no latency data available and the "total_min" is
set to "N/A" which cannot be converted to a float in Python and
results in an exception.  Check for this condition before processing
the value -- we can ignore the case where it occurs because that
trial exit state is handled elsewhere.

ensure minimum latency data exists before processing it

---

profile-builder.py

- Setting rate to mpps makes the behavior consistent with
binary-search.py and trex-txrx.py.
- This change makes it possible to change from trex-txrx.py to
trex-txrx-profile.py with as little as no other changes.

profile-builder.py: change rate from pps to mpps

---

trex-txrx.py

- When a stream has to be broken down into substreams, other streams
are unaware that this happens.  When streams where chained together,
a stream (say the first stream -- or at least the last substream of
the first stream) would be pointing at the incorrect stream name for
the next stream in the chain (the second stream) if it had been
broken into substreams.
- This patch changes substream names so that the first substream
maintains the same name as the non-broken down stream.  This leads
to a slightly odd naming scenario:
1. default_stream_0->1_UDP_segment_1
2. default_stream_0->1_UDP_segment_1_sub_2
3. default_stream_0->1_UDP_segment_2
4. default_stream_0->1_UDP_segment_2_sub_2
5. default_stream_0->1_UDP_segment_3
6. default_stream_0->1_UDP_segment_3_sub_2
as opposed to the old (and …

trex-txrx.py: bugfix for sub stream names

---

binary-search.py
launch-trex.sh
trex-txrx-profile.py
trex-txrx.py

- The TRex scripts here are originally designed for physical-functions (PFs)
- This adds the necessary function to work with VFs, if those VFs are
supported by TRex.  To date, we know VFs frpm Intel X710-based NICs
work with TRex.
- Add option to allow no promisc mode for Trex interfaces
- Allow the user to specify the CPUs used when launching TRex.  This
may be of use when you do not want to assume all nohz_full CPUs
are to be used for TRex.

Add support for virtual-functions (VFs)
